'''Autor: Jonatan Paschoal, 22/04/2020. Operadores com o função: pow(x,y)=x**y'''
print('--------------------------------------------')
print('Resolva a seguinte expressão numérica.')
print('a {[ b + c ( d x e )] f + (g - h)}')
a = int(input('Digite o valor de a: '))
b = int(input('Digite o valor de b: '))
c = int(input('Digite o valor de c: '))
d = int(input('Digite o valor de d: '))
e = int(input('Digite o valor de e: '))
f = int(input('Digite o valor de f: '))
g = int(input('Digite o valor de g: '))
h = int(input('Digite o valor de h: '))
resultado = a*(( b + c * ( d * e )) * f + (g - h))
print('O resultado da expressão.')
#print('{} {[ {} + {} ( {} x {} )] {} + ( {} - {} )} é {}'.format(a,b,c,d,e,f,g,h)) '''<----- corrigir essa linha'''
print(a,'{[',b,'+',c,'(',d,'x',e,')]',f,'+ (',g,'-',h,')} é', resultado)
print('--------------------------------------------')