print('-----'*10)
frase1 = input('  Digite uma frase: ')
print('  A frase >> {} << será "fatiada".'.format(frase1))
print(' ',frase1[3])
print(' ',frase1[6:])
print(' ',frase1[:6])
print(' ',frase1[4:10])
print(' ',frase1[::2])
print('  O tamanho da frase é {} '.format(len(frase1)))
print('-----'*10)
print('  O caracter "a" repete {} vezes.'. format(frase1.count('a')))
print('  O caracter "e" repete {} vezes.'. format(frase1.count('e')))
print('  O caracter "i" repete {} vezes.'. format(frase1.count('i')))
print('  O caracter "o" repete {} vezes.'. format(frase1.count('o')))
print('  O caracter "u" repete {} vezes.'. format(frase1.count('u')))
print('-----'*10)
print('  Tudo maiúsculo! --> {}'.format(frase1.upper()))
print('  Tudo minúsculo! --> {}'.format(frase1.lower()))
print('  Tudo captalizado! --> {}'.format(frase1.capitalize()))
print('  Título! --> {}'.format(frase1.title()))
print('-----'*10)
print('  {} existe a palavra "física" na frase.'.format('física' in frase1))
print('  Frase em forma de lista: {}'.format(frase1.split()))
print('-----'*10)